services:
  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    build: .
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - REDIS_PASSWORD=redispassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_SECRET=redissecret
      - MongoUrl=mongodb://piyush:piyushmongodb@mongo:27017/?authSource=admin
    command: npm run start
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=piyush
      - MONGO_INITDB_ROOT_PASSWORD=piyushmongodb
      - MONGO_INITDB_DATABASE=app
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redispassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_SECRET=redissecret

volumes:
  mongo-db:
